
logging:
  level:
    root: INFO
spring:
  application:
    name: kafka-demo
# Database Config
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/kafkaDemo
    username: root
    password: Akash@12345


kafka-config:
  bootstrap-servers: localhost:9092
  schema-registry-url-key: schema.registry.url
  schema-registry-url: http://localhost:8081
  topic-name: auth-topic
  num-of-partitions: 1
  replication-factor: 1

kafka-producer-config:
  key-serializer-class: org.apache.kafka.common.serialization.StringSerializer
  value-serializer-class: io.confluent.kafka.serializers.KafkaAvroSerializer
  acks: all
  batch-size: 16384
  linger-ms: 5
  request-timeout-ms: 60000

kafka-consumer-config:
  key-deserializer-class: org.apache.kafka.common.serialization.StringDeserializer
  value-deserializer-class: io.confluent.kafka.serializers.json.KafkaJsonSchemaDeserializer

kafka-streams-config:
  application-id: kafka-demo
  input-topic-name: auth-topic
  output-topic-names:
    - subscriber
    - patient
    - mycase
    - service